### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by WindMarx** [xiaoman-zhang/PMC-VQA#12]
非常感谢你们分享的代码，但是看了代码之后发现有很多错误的地方，比如：from model.QA_model import QA_model 应该是 from models.QA_model import QA_model，还有很多类的命名令人疑惑的比如：class Binary_VQA_Model(nn.Module): 这个应该不是二元的VQA模型吧
请问这个代码会继续修改吗

**Comment by noviceswing** [comment]
你好，请问你解决这些代码问题了吗？
