### ISSUE TITLE
The question about task_type=TaskType.LM in MedVInT_TE

### ISSUE THREAD

**Issue by yuliang-liang** [xiaoman-zhang/PMC-VQA#7]
Hello, I have some problem about the MedVInT_TE in
“src/MedVInT_TE/models/llama/vqa_model.py     Line52”

```
def get_peft_config(peft_args: PEFTArguments):
    if peft_args.peft_mode == "lora":
        peft_config = LoraConfig(
            task_type=TaskType.LM, inference_mode=False,
            r=peft_args.lora_rank,
            lora_alpha=32, lora_dropout=0.1
        )
```
I noticed that TaskType.LM is not included as one of the task types in PEFT. Could you clarify if TaskType.LM refers to an embedding-typed model for Lora that you created? I made changes to the code, adjusting the task_type, but I am still encountering issues when loading the official checkpoint.

**Comment by xiaoman-zhang** [comment]
Yes, we modified the Peft package for the MedVInT_TE, and  I have uploaded the modified peft package in the 'src/MedVInT_TE/' path.
